export enum activeGroupChatActionTypes {
  SET_ACTIVE_GROUP_CHAT = 'SET_ACTIVE_GROUP_CHAT',
  ADD_MESSAGE_TO_ACTIVE_GROUP_CHAT = 'ADD_MESSAGE_TO_ACTIVE_GROUP_CHAT',
  REMOVE_MESSAGE_FROM_ACTIVE_GROUP_CHAT = 'REMOVE_MESSAGE_FROM_ACTIVE_GROUP_CHAT',
}
