export enum activeChatActionTypes {
  SET_ACTIVE_CHAT = 'SET_ACTIVE_CHAT',
  ADD_MESSAGE_TO_ACTIVE_CHAT = 'ADD_MESSAGE_TO_ACTIVE_CHAT',
  REMOVE_MESSAGE_FROM_ACTIVE_CHAT = 'REMOVE_MESSAGE_FROM_ACTIVE_CHAT',
}
