export enum usersActionTypes {
  INIT_USERS_STATE = 'INIT_USERS_STATE',
  ADD_USER_TO_USERS = 'ADD_USER_TO_USERS',
  UPDATE_CHATLIST_OF_USER = 'UPDATE_CHATLIST_OF_USER',
  UPDATE_NICK_OF_USER = 'UPDATE_NICK_OF_USER',
}
